sudo: required

language: python
python:
  - 3.6

matrix:
  include:
    - compiler: gcc
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install:
        - sudo apt-get install -qq gcc-6
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
      before_script:
        - python3 -m pip install numpy sphinx
      script:
        - ./configure
        - make install
        - make check
        - git clean -xdf
        - python3 setup.py develop
        - python3 setup.py test
        - python3 setup.py doctest
        - git clean -xdf
        - python3 setup.py install
        - python3 setup.py test
        - python3 setup.py doctest

    - compiler: clang
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y valgrind
        - python3 -m pip install numpy sphinx
        - export CC=clang
      script:
        - ./configure
        - make install
        - make memcheck
        - git clean -xdf
        - python3 setup.py develop
        - python3 setup.py test
        - python3 setup.py doctest
        - git clean -xdf
        - python3 setup.py install
        - python3 setup.py test
        - python3 setup.py doctest

    - language: objective-c
      os: osx
      compiler: clang
      before_install:
        - brew install python3
      before_script:
        - export CC=clang
      script:
        - ./configure
        - make install
        - make check
        - git clean -xdf
        - python3 setup.py develop
        - python3 setup.py test
        - git clean -xdf
        - python3 setup.py install
        - python3 setup.py test

    - compiler: conda
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install:
        - sudo apt-get install -qq gcc-6
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        - bash Miniconda3-latest-Linux-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - conda update --yes conda
        - conda install --yes conda-build
        - conda install --yes anaconda-client
      script:
        - cd xnd-all
        - git fetch --unshallow
        - cd scripts
        - ./conda-install.sh
        - export LIBNDTYPES=`conda build --output build/ndtypes/.conda/libndtypes`
        - export NDTYPES=`conda build --output build/ndtypes/.conda/ndtypes`
        - export LIBXND=`conda build --output build/xnd/.conda/libxnd`
        - export XND=`conda build --output build/xnd/.conda/xnd`
        - export LIBGUMATH=`conda build --output build/gumath/.conda/libgumath`
        - export GUMATH=`conda build --output build/gumath/.conda/gumath`
        - export XNDTOOLS=`conda build --output build/xndtools/.conda`
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $LIBNDTYPES --user xnd --label dev --skip-existing; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $NDTYPES --user xnd --label dev --skip-existing; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $LIBXND --user xnd --label dev --skip-existing; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $XND --user xnd --label dev --skip-existing; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $LIBGUMATH --user xnd --label dev --skip-existing; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $GUMATH --user xnd --label dev --skip-existing; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $XNDTOOLS --user xnd --label dev --skip-existing; fi

    - language: objective-c
      os: osx
      compiler: conda
      install:
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        - bash Miniconda3-latest-MacOSX-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - export CC=clang
        - conda update --yes conda
        - conda install --yes conda-build
        - conda install --yes anaconda-client
      script:
        - cd xnd-all
        - git fetch --unshallow
        - cd scripts
        - ./conda-install.sh
        - export LIBNDTYPES=`conda build --output build/ndtypes/.conda/libndtypes`
        - export NDTYPES=`conda build --output build/ndtypes/.conda/ndtypes`
        - export LIBXND=`conda build --output build/xnd/.conda/libxnd`
        - export XND=`conda build --output build/xnd/.conda/xnd`
        - export LIBGUMATH=`conda build --output build/gumath/.conda/libgumath`
        - export GUMATH=`conda build --output build/gumath/.conda/gumath`
        - export XNDTOOLS=`conda build --output build/xndtools/.conda`
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $LIBNDTYPES --user xnd --label dev --skip-existing; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $NDTYPES --user xnd --label dev --skip-existing; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $LIBXND --user xnd --label dev --skip-existing; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $XND --user xnd --label dev --skip-existing; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $LIBGUMATH --user xnd --label dev --skip-existing; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $GUMATH --user xnd --label dev --skip-existing; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $XNDTOOLS --user xnd --label dev --skip-existing; fi

env:
  global:
    - secure: "t8pu5rMxKywwSUKJULFYIIGi0y1MqZ7kilpUE8jyuxQz26DtKCQok1FosgEOTAwM3wsERMQTGjxIRysRm5cYrt4V3hHe/qtMkLV8KrNtkMX31/iJhix+KyE2x1pk3cUIXiGE64qubzlcPakMIJcOnx9a9FWKaKeopiLx05YAG303j2SxqJM6Js4cZYoZlYKbDHLkEyyTr8oE5ttR/L3rsHvzQxWhbOlieIKIj9lz1tusecy86o6S7QQn7wIqxwQ58QPL7vW4oU3TO9pynG5ePwJ7CZAc/KW/n42i1ufk4cnyF5Cdk6AWhmtdxvHn916uDFuz42Wbo6ks/TBLu2EKtOM+z5es1/GEMOI3IKdbhu66R9XjLasrtlZwLvYi5/yPKlov2QFn5Q5OhW9cKUhO34ZF4/3AjntW/fXz2VqmzTR8EZQ/nzfeMr0fqzTj2cHOk2/Rv4ev4v3GK42tkqfHMUQe4VI0rYCp839BUqqoVjsb9/gB7AGT4qkKQYI/UBpYG0PfsBKli3m2ujaW1nnkVMK5ETMXxa0e9IdrAa5yV4nkJ6XuUdoh3uIftMQ+P5/xi4GRk3iHzoOmU+u+K0YrOTgiUJlsFJm/wAg5XapqsSL5PtF7q0msrxw/ZJiFMeOxZ7qOml8W04WWUrbdpQ2Ph2tbBs/iTAKxxg10P0857Fs="
